[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# 301 redirects for blog to insights migration
[[redirects]]
  from = "/blog"
  to = "/insights"
  status = 301

[[redirects]]
  from = "/blog/*"
  to = "/insights/:splat"
  status = 301

# 301 redirect for updated blog post slug
[[redirects]]
  from = "/insights/maximizing-your-retirement-savings-2024"
  to = "/insights/maximizing-your-retirement-savings-2025"
  status = 301

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://uvt95dbx.apicdn.sanity.io https://www.googletagmanager.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: blob: https: https://images.unsplash.com https://uvt95dbx.apicdn.sanity.io https://cdn.sanity.io; connect-src 'self' https://uvt95dbx.apicdn.sanity.io https://uvt95dbx.api.sanity.io https://web-production-7aa44.up.railway.app https://www.google-analytics.com https://analytics.google.com https://region1.google-analytics.com https://*.google-analytics.com; frame-ancestors 'none';"

# Admin route security - extra protection for admin dashboard
[[headers]]
  for = "/admin"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow, noarchive, nosnippet"
    X-Frame-Options = "DENY"
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

# Cache headers for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"